static_announcements = {
  "Do not use toilet while the train is on station":"dont_use_toilet",
  "Passenger should buy ticket  before entering platform":"buy_ticket_before",
  "Passenger should take care of their luggage":"passengers_care_luggage",
  "Inflammable materials are prohibited":"inflammlabe",
  "Do not make platform dirty and help us to keep it clean":"platform_clean",
  "Switch off fans and light’s while not in use":"switch_off_fan",
  "Use foot over bridge to go from one PF to another":"use_foot_over_bridge1",
  "Transfer of reserved ticket":"transfer_reserved_tickets",
  "welcome to station":"welcome_to_station",
  "Suspicious articles are prohibited on station":"suspicious_things_prohb",
  "No crossing of railway lines":"no_crossing",
  "Passenger should not take any suspicious thing from the another unknown passenger":"not_take_any_suspicious",
  "take care of childrens":"take_care_childrens",
  "Do not enter while train in motion":"not_enter_train_in_motion",
  "Smoking is strictly prohibited":"smoking_punishable",
  "welcome message":"welcome_message",
  "Wish you a happy journey":"happy_travel",
  "Ticketless travel is punishable":"without_ticket",
  "Buy your ticket from counters":"buy_ticket_from_counter",
  "Be careful from thiefs":"be_careful",
  "Lady passengers to avoid windows and doors":"lady_passengers_avoid_door",
  "Take care of your children during travel":"care_childrens",
  "Please keep station clean":"keep_station_clean2",
  "Do not accept any eatable from strangers":"not_accept_food_from_strangers",
  "Do not touch suspicious articles":"not_touch_suspicious_things",
  "Do not use latrine while train is at station":"not_use_toilet_on_station",
  "Do not travel without proper ticket":"not_travel_without_ticket",
  "Use bins provided":"use_dustbins",
  "tickets are not transferable":"ticket_not_transferable",
  "Use foot over bridge":"use_foot_over_bridge1",
  "keep station clean":"keep_station_clean3",
  "Take care your children during travelling":"take_care_children",
  "Passengers are requested not panic in case of fire in coach":"passengers_not_panic_fire_in_coach",
  "Passengers are requested not to touch or take any suspicious article":"passengers_not_touch_suspicious_things",
  "please not travel without ticket":"passengers_not_travel_without_ticket",
  "please buy proper tickets":"buy_proper_tickets",
  "Do not enter platform without proper journey ticket or platform ticket":"not_enter_without_platform_ticket",
  "We wish you happy and safe journey":"happy_and_safe_travel",
  "Railway station welcome all passengers":"railway_station_welcome_passenger",
  "Please do not accept eatable from strangers":"Not_take_food_from_strangers",
  "Cigarette smoking at the platform is punishable":"no_smooking",
  "Do not throw a waste material around please use the dustbins provided":"Not_throws_things_use_dustbins",
  "Please switch off light, fan":"Switch_off_light_fan",
  "Not use toilets when train is on station":"Not_use_toilets_when_train_on_station",
  "Please carry a valid travel ticket":"carry_platform_ticket",
  "Rooftop travelling cause death.":"Rooftop_travelling_cause_death",
  "help us to keep the platforms and trains clean by using the dust bins":"Keep_railway_station_clean_not_throw_things",
  "keep platforms and trains clean please use dustbin":"keep_platforms_and_trains_clean_please_use_dustbin",
  "Not blocking the Bio-Toilets by throwing the other things.":"Not_throw_things_in_toilet",
  "Please avoid boarding and de-boarding the moving train":"Not_enter_when_train_in_motion",
  "do npt accept food from strangers":"Not_accept_food_from_strangers",
  "please carry identity card":"carry_identity_card",
  "Carry platform ticket before entering platform":"Carry_platform_ticket_before_entering_platform",
  "without ticket travel punishable":"without_ticket",
  "please Switch off lights and fans when not in use":"Switch_off_lights_and_fans_not_use",
  "thank you for Keeping station clean":"Keep_station_clean1",
  "not smoke on platform":"not_smoke_on_platform",
  "please buy proper tickets":"buy_tickets",
  "not use toilets when train is on station":"not_use_toilets_when_train_is_on_station",
  "Gents do not travel in ladies coach":"Gents_not_travel_in_ladies_coach",
  "Buy platform tickets":"Buy_platform_tickets",
  "Food is available at station":"Food_available_station",
  "Park your vehicles in parking area":"Park_vehicle_in_parking_area",
  "do not carry inflammable things in train":"Not_carry_inflammable_things_in_train",
  "welcome to railway station":"welcome_to_railway_station",
  "Crossing the railway track is an offence":"track_crossing_punishable",
  "Child help line number available":"Child_help_line_available",
  "Passangers do not throw articles use dustbins":"do_not_throw",
}



def staticAnnouncements():
  return static_announcements







airport_static = {
  "Ladies and Gentlemen":"ladies gentlemen",
  "Thank you":"Thank you",
  "Have a pleasant flight":"flight pleasant",
  "May we have your attention please":"please attention (observe sign use towards sign themselves)",
  "Thank you for travelling with our Airlines":"Our Airlines travelling thank you",
  "Thank you for travelling with us.":"us (we) with travelling thank you",
  "Till then Goodbye":"Till then Goodbye",
  "On Time Arrival":"Arrival time",
  "Ahead of Schedule":"Schedule ahead",
  "Collect your checked-in baggage":"Your Checked in baggage collect",
  "I repeat":"I repeat",
  "Enjoy your flight.":"Flight enjoy",
  "We ask that you please fasten your seatbelts at this time and secure all baggage underneath your seat or in the overhead compartments.":"We ask you please this time your seatbelt fasten and all baggage your seat underneath or compartment overhead secure",
  "We also ask that your seats and table trays are in the upright position for take-off.":"We ask your seat and table trays take off time position upright",
  "Please turn off all personal electronic devices, including laptops and cell phones.":"Please all personal electronic device ,including laptops, cell phones turn off",
  "Smoking is prohibited for the duration of the flight.":"Flight duration (time) smoking prohibited",
  "Good afternoon passengers":"Good afternoon passengers",
  "We are now inviting those passengers with small children, and any passengers requiring special assistance, to begin boarding at this time.":"Passenger small children with we inviting now, and any passenger special assistance requiring, boarding time begin.",
  "Please have your boarding pass and identity card ready":"Please your boarding pass and (plus) identity card ready",
  "Our business Passengers please board as per your own convenience.":"our passengers business please your convenience board",
  "we are sorry for this delay and sincerely apologize for any inconvenience caused to you.":"we sincerely apologize inconvenience (problem) caused (happen) you (all) reason flight delay",
  "our customer service staff will be available for any assistance you may require.":"any assistance (help sign use towards signer, inside) require our customer service staff available (have)",
  "We thank you for your patience.":"your patience we thank you",
  "Passengers are requested to kindly pass through Security Check and await departure announcement in the ground floor/ first floor security area":"Passenger requested kindly first security check and (next) departure announcement await where ground floor /first floor security area",
  "Please note only one piece of handbags will be permitted on board.":"please remember board handbags permitted only one",
  "You are requested to contact our customer service staff immediately.":"you requested immediately contact our customer service staff",
  "For your safety and comfort, please remain seated":"Your safety and comfort please seated remain",
  "Guests wishing to use their mobile phones may do so now":"Guests who wishing (want) mobile phone use now, may do so (possible)",
  "Please take care while opening the overhead compartments as items may have moved during the flight and could fall out on you or someone else":"Please take care (careful) while overhead compartment open, during flight may items move and possible you or someone (different person) fall out",
  "We look forward to welcoming you on board soon":"We board soon. you welcoming",
  "If you're connecting on to a domestic flight today you must complete immigrations":"If you domestic flight today connected you complete immigrations",
  "Clear customs and hand over the bags to Guest Services Crew for transfer to your final destinations":"Clear customs and bags over hands guest services crew transfer your destinations final",
  "If you are connecting on to an international flight then you are not required to clear the immigration and customs formalities":"If you international flight connecting you immigration and customs formalities clear require (want) not",
  "Before disembarking, may we request you to leave the blankets on the seats?":"Disembarking before, you request blankets seats leave (put)",
  "Before disembarking may we request you to kindly detach the headsets and leave them on the seats along with the blanket":"Disembarking before you request kindly headsets detach and blanket along (shaking sign of 2) seats leave (put)",
  "Your considerate gesture will aid our staff in speedy collection and we appreciate your kind co-operation":"Your gesture our staff aid collection speedy and we your co -operation kind appreciate",
  "During this special time of the year, eating, drinking and smoking in public places is not permitted during daylight hours.":"Year special time public places daylight hours eating, drinking, and smoking permitted not",
  "The local CISF regulations in India prohibits carriage of liquids exceeding 100ml as part of hand baggage on Domestic flights":"CISF local India in regulations have carriage exceeding 100ml liquid hand baggage inside domestic flights prohibits",
  "Please do not hesitate to call any of the cabin crew members.":"Any cabin crew members call hesitate not",
  "Please refer to the safety instruction card placed in the seat back pocket in front of you.":"please refer safety instruction card placed (where) back pocket seat you front",
  "To operate your seatbelt, insert the metal tip into the buckle to tighten pull the loose end of the strap":"Your seatbelt operate (use) , buckle insert metal tip tighten strap loose end pull",
  "To open please lift the buckle while seated please keep your seatbelt fastened at all times.":"open (+want) buckle lift while seated all times fastened your seatbelt",
  "If there is a loss in cabin pressure oxygen mask will drop down automatically from the panel above you.":"If cabin pressure loss automatically oxygen mask, panel above you (show by moving neck upward) drop down",
  "Remain seated and pull a mask down sharply to start the oxygen flow. Place the Mask over your nose and mouth and breathe normally.":"Seated remain and sharply mask down pull oxygen flow start nose, mouth mask breathe normally.",
  "Place your mask on first before assisting others":"first self mask after others assisting (help)",
  "In case of an evacuation fluorescent strips along the floor will guide you to the nearest exit.":"Evacuation case (time) floor fluorescent strip you guide nearest exit",
  "In case of an evacuation the escape part emergency light fitted on the floor shall guide you to the nearest exit.":"Evacuation case escape floor fitted emergency light guide you nearest exit",
  "The exit in the forward and the backward are equipped with a slide raft additionally a life raft is also carried on the aircraft which is located in the alt overhead Bin":"Forward exit and aircraft carried backward equipped slide raft additionally life raft located (where) alt bin overhead",
  "Government regulation require that all electronic devices be switched off and mobile phone should be switched off or in the flight mode for the entire duration of the flight":"Government regulation require what entire during (full +time) flight all electronic devices switch off and mobile phone switch off or flight mode",
  "In the unlikely event of a water landing take out the life jacket placed in a pouch under your seat and slip it over your head place the strap around your waist and secure it into the buckle the strap can be adjusted as required.":"If water landing unlikely event (problem happen) your seat under pouch life jacket have and your over head slip strap waist around and buckle secure strap adjusted require (possible)",
  "Pull the red tabs to inflate and blow the red tubes to inflate it further":"red tabs pull inflate and blow red tubes further inflate",
  "Please note that if you leave through the main exit doors then the life jacket should be inflated just before leaving the aircraft.":"Please note (remember) if you main door exit leave (walk downward) aircraft leaving before inflated life jacket",
  "However if you are going to evacuate to one of the over wing exit then the life jacket that should be inflated after leaving the aircraft only.":"If you over wing exit evacuate going then only aircraft leaving after life jacket inflated",
  "Leaving the aircraft, you must board the nearest raft (to be read only if the aircraft has either side rafts or life raft)":"Aircraft leaving (out) , you nearest raft board (read only if aircraft either side rafts or lift raft)",
  "Tempering with the life jacket or removal of it from the aircraft without the authorization by a cabin crew member is strictly prohibited and is a punishable offence.":"Life jacket tempering or removal without cabin crew member authorization from aircraft prohibited strictly and offence (crime) punishable",
  "Ladies and gentlemen, on behalf of the crew I ask that you please direct your attention to the monitors above as we review the emergency procedures":"Ladies and gentlemen, crew behalf please your attention monitors above emergency procedures we review",
  "Take a minute to locate the exit closest to you":"Exit you closest locate minute take (possible)",
  "Note that the nearest exit may be behind you.":"Note your behind exit nearest may be",
  "Count the number of rows to this exit.":"This exit rows number count",
  "Should the cabin experience sudden pressure loss, stay calm and listen for instructions from the cabin crew":"Pressure loss cabin experience sudden, calm stay and (plus) cabin crew instruction listen",
  "Oxygen masks will drop down from above your seat.":"Oxygen mask your seat drop down (look above)",
  "Place the mask over your mouth and nose, like this.":"Mask your mouth and nose like (example) this",
  "Pull the strap to tighten it.":"Tighten strap pull",
  "If you are traveling with children, make sure that your own mask is on first before helping your children.":"If you children with traveling, your children help before first your mask",
  "In the unlikely event of an emergency landing and evacuation, leave your belongings behind.":"If (Problem Situation) emergency landing and evacuation want, your belongings behind leave",
  "Life rafts are located below your seats and emergency lighting will lead you to your closest exit and slide.":"Your seat below life rafts and (plus) your exit closest and slide emergency lighting lead (guide)",
  "We ask that you make sure that all carry-on luggage is stowed away safely during the flight.":"We ask You make sure (remember) all carry on luggage flight during safely stowed away",
  "While we wait for take off, please take a moment to review the safety instruction card in the seat pocket in front of you.":"While we take off wait, you front seat pocket safety instruction card please review",
  "Ladies and gentlemen, I’d like to direct your attention to the television monitors.":"Ladies and gentlemen, your attention television monitors direct",
  "We will be showing our safety demonstration and would like the next few minutes of your complete attention.":"We safety demonstration showing and your next few minutes attention complete",
  "If there is no video system and the flight attendants do the demonstration themselves in the aisles, the announcement might be as follows.":"If video system no and announcement follows aisles flight attendant themselves demonstration",
  "Now we request your full attention as the flight attendants demonstrate the safety features of this aircraft.":"We request your attention full now flight attendants this aircraft safety features demonstrate",
  "Either on the video screen, or live, the safety demonstration might sound like this.":"Video screen, or live, this sound may be safety demonstration",
  "If it is a video presentation, it usually starts with a friendly welcome from the airline, the reminder of the seat belt signs currently illuminated, the seat back and tray table restriction, as well":"As the carry-on luggage.",
  "If video presentation, airlines from friendly welcome starts, seat belt signs reminder currently illuminated, seat back and tray table restriction, plus luggage carry":"When the seat belt sign illuminates, you must fasten your seat belt. Insert the metal fittings one into the other, and tighten by pulling on the loose end of the strap.",
  "When seat belt sign illuminates, you seat belt fasten must. metal fitting one into other insert, and strap loose end pulling tighten (sign of tighten is same as we tight belt and shown by expression)":"To release your seat belt, lift the upper portion of the buckle.",
  "Your seat belt release, buckle upper portion lift":"We suggest that you keep your seat belt fastened throughout the flight, as we may experience turbulence.",
  "We suggest flight throughout (full +time) your seat belt fastened, if we turbulence experience":"There are several emergency exits on this. Please take a few moments now to locate your nearest exit.",
  "This several exits emergency. Please moment located your exit nearest":"In some cases, your nearest exit may be behind you.",
  "Some situation, your exit nearest you behind may be":"If we need to empty the aircraft, floor-level lighting will guide you towards the exit.",
  "If we aircraft empty need, floor level lighting you exit guide":"Doors can be opened by moving the handle in the direction of the arrow. Each door is equipped with an inflatable slide which may also be detached and used as a life raft.",
  "Arrow direction handle moving door opened. each door slide inflatable equipped detached may and same life raft used":"Oxygen and the air pressure are always being monitored. In the event of a decompression, an oxygen mask will automatically appear in front of you.",
  "Air pressure and oxygen monitored always. you front automatically oxygen mask appear":"To start the flow of oxygen, pull the mask towards you.",
  "Oxygen flow start, mask pull towards you (toward signer)":"Place it firmly over your nose and mouth, secure the elastic band behind your head, and breathe normally.",
  "Your nose and mouth over place, your head behind elastic band secure, and breathe normally":"Although the bag does not inflate, oxygen is flowing to the mask.",
  "When bag inflate not, mask oxygen flowing":"If you are travelling with a child or someone who requires assistance, secure your mask on first, and then assist the other person.",
  "If you child or someone (any + person) who assistance (help) requires with travelling, first your mask, and then other person assist (help)":"Keep your mask on until a uniformed crew member advises you to remove it.",
  "Your mask keep (same) until (time +when) uniformed crew member you remove advises":"In the event of an emergency, please understand the bracing position.",
  "Emergency event, please bracing position understand":"Lean forward with your hands on top of your head and your elbows against your thighs.",
  "Your hands your head top forward lean and your elbows thighs against":"Ensure your feet are flat on the floor.",
  "Ensure (remember) your feet floor flat":"A life vest is located in a pouch under your seat or between the armrests.",
  "A life vest pouch located your seat under or armrests between":"When instructed to do so, open the plastic pouch and remove the vest.",
  "When instruction, plastic pouch open and vest remove":"Slip it over your head.",
  "Your head over slip":"Pass the straps around your waist and adjust at the front.",
  "Your waist around Strap pass and front adjust":"To inflate the vest, pull firmly on the red cord, only when leaving the aircraft.",
  "Vest inflate, red cord firmly pull, only when aircraft leaving":"If you need to refill the vest, blow into the mouthpieces.",
  "If you vest refill need, mouthpieces blow in":"Use the whistle and light to attract attention. Also, your seat bottom cushion can be used as a flotation device.",
  "Whistle use and light attract attention. your seat cushion bottom device flotation used":"Pull the cushion from the seat, slip your arms into the straps, and hug the cushion to your chest.",
  "From seat cushion pull, your arms straps slip, and your chest cushion hug":"At this time, your portable electronic devices must be set to ‘airplane’ mode until an announcement is made upon arrival.",
  "This time your portable electronic devices airplane mode must until (time +number +what) arrival announcement.":"We remind you that this is a non-smoking flight.",
  "We remind (inform) you this flight non smoking":"You will find this and all the other safety information in the card located in the seat pocket in front of you.",
  "You find this and all other safety information card located you front seat pocket":"We strongly suggest you read it before take-off.",
  "We suggest strongly take off before you read":"If you have any questions, please don’t hesitate to ask one of our crew members.",
  "If you any question, please crew member ask hesitate not":"We wish you all an enjoyable flight.",
  "We you all flight enjoyable wish":"I would like to enquire if you are pregnant as we need to brief all pregnant passengers on safety aspects.",
  "I enquire if you pregnant we brief need safety aspects all pregnant passengers":"Extremely sorry for the misunderstanding thank you for your time have a nice flight",
  "Misunderstanding sorry your time thank you flight nice":"Congratulate and continue with the briefing mam with your safety in mind we would like to preview on some important points",
  "Congratulation and your mind (remember) safety mam briefing continue we some important point preview":"I request you to drink plenty of water to stay hydrated",
  "I request stay hydrated water drink plenty":"Please do some calf exercises to help with better blood circulation",
  "Please some calf exercises do help blood circulation better":"Avoid sitting still for a long time and try to walk around the aircraft whenever possible",
  "Long time sitting avoid and try whenever possible aircraft around walk":"Please adjust the seat belt strap low and comfortably so it fits below the baby bump should you require any further assistance?",
  "Please seat belt strap adjust low and comfortable so baby bump below fits any further assistance you require (expression)?":"Thank you as part of the safety instructions I would like to assist you to understand all our safety measures.",
  "Safety instruction thank you, I assist (help) our all safety measures understand":"This is the safety instruction card please read it carefully.",
  "Safety instruction card please carefully read":"This is your seatbelt and this is how you tie it, untie it and adjust it.",
  "Your seatbelt this, tie how, untie, adjust":"Are you comfortable with the seat belt?",
  "Seat belt comfortable (expression of question)?":"In case of a loss in cabin pressure this is what the deployed oxygen mask look like. are you comfortable with this?",
  "Cabin pressure loss situation oxygen mask deployed look like what. you comfortable (expression of question)?":"In the unlikely event of a water landing take out the life jacket placed in a pouch under your seat and slip it over your head place the strap around your waist and secure it into the buckle the strap can be adjusted as required.",
  "If water landing unlikely event (problem happen) your seat under pouch life jacket have and your over head slip strap waist around and buckle secure strap adjusted require (possible)":"Pull the red tabs to inflate and blow the red tubes to inflate it further",
  "red tabs pull inflate and blow red tubes further inflate":"Should you require any assistance you may call any of the cabin crew by pressing the Call button, which is located in the panel above you right here?",
  "Any assistance (help) you require (want) cabin crew call, call button pressing located (where) you right panel above":"To the person sitting closest to the hearing impaired passenger sir Mam may I request you to assist one of our passengers seated near you?",
  "Hearing impaired passenger closest sitting sir mam, I request one our passengers you near seated assist (help) may (possible)":"If yes thank you, we really appreciate your effort assistance thank you.",
  "If yes thank you, your assistance (help) effort we really appreciate thank you":"If no look for another buddy to assist",
  "If another buddy assist look no":"Since you are travelling alone, should you require any assistance you may please call any of the cabin crew by pressing this Call button.",
  "If you alone travelling Any assistance you require any cabin crew call right call button pressing":"I would like to inform you that I am going to stow your carry-on baggage in the overhead Bin right over here.",
  "I like (want) inform your carry on baggage bin overhead right I stow":"You must not leave the aircraft without the assistance of any of the cabin crew.",
  "any cabin crew assistance must aircraft leave (out)":"To operate your seatbelt, insert the metal tip into the buckle. To tighten pull loose end of the strap.",
  "Your seatbelt operate (use) , buckle insert metal tip tighten strap loose end pull":"To open please lift the buckle while seated please keep your seatbelt fastened at all times.",
  "open (+want) buckle lift while seated all times fastened your seatbelt":"To another passenger sir madam may I please request you to help us take care of this young passenger of us",
  "Passenger another sir madam I request please help (towards ourself) young passenger take care (care)":"Should you require any assistance you may please call any of the cabin crew by pressing this Call button.",
  "Any assistance you require any cabin crew call right call button pressing":"Since you are traveling with an infant I would like to brief you on the safety aspects of the aircraft",
  "If you infant with traveling, I like (want) you aircraft aspect safety brief":"Do not put the seat belt around the Infant throughout the flight",
  "Throughout (full time) flight infant around seatbelt no":"Hold the Infant in your arms feed the baby for takeoff and landing to avoid any discomfort in the ears",
  "Takeoff and landing infant hold your arm feed any ears discomfort (problem) avoid":"In case of loss in cabin pressure four oxygen mask will deploy from the panel above you",
  "Cabin pressure loss situation oxygen mask deploy panel above":"Please wear your mask first and then assist your baby.",
  "Please first your (yourself) mask and your baby assist":"For your convenience we have a diaper changing table in the lavatory.",
  "Your convenience lavatory diaper changing table have":"Should you require any assistance you may please call any of the cabin crew by pressing this Call button.",
  "Any assistance you require any cabin crew call right call button pressing":"May I take a moment of yours?",
  "I your moment want possible (expression)?":"I would like to share certain safety instructions with you.",
  "I some safety instructions share":"I would like to inform you about three very important points where when and how",
  "I like (want) inform important point very three where when and how":"Where you are seated in the row from the nearest floor level exit?",
  "Floor level exit nearest row you seated where":"you must evacuate when the aisles are clear and the floor of evacuation has ceased.",
  "When aisles clear evacuate you must and floor evacuation ceased":"During evacuation how can I help you out of your without causing you for the pain or injury.",
  "I help you out seat pain or injury causing (happen) without (not) evacuation how":"Should you need any special assistance in evacuating the cabin please inform the cabin crew?",
  "Cabin Evacuating Any special assistance (help) need (expression of question)? please cabin crew inform":"Remove the cover and place it under the seat in front.",
  "Cover remove and seat front place under":"Pull down the handle, the exit will fall inside and the side will inflate throw it outside towards the front.",
  "Handle pull, exit inside fall and side towards front outside inflate throw":"Point Toward the nose of the aircraft",
  "Aircraft towards nose point":"If the slide doesn't inflate pull the red handle located inside",
  "Inside red handle pull if slide inflate doesn't":"point towards the red manual inflation handle",
  "Red manual handle inflate point":"Pull down the handle and release it immediately the exit window will open outwards and upwards and the slide will inflate automatically.",
  "Handle pull down and release immediately outward and upward exit window open and automatically slide inflate":"Move out of the aircraft immediately.",
  "Do not open if you see fire, water, any obstruction etc.":"Immediately aircraft move out. if you fire, water, any obstruction etc. see open not",
  "For any query please contact us":"Any query contact please",
  "Please remember this exit should be open only when you hear a command passenger evacuate, Evacuate, Evacuate from the captain or any of the cabin crew members":"Please remember from captain or any cabin crew members passenger evacuate, evacuate, evacuate when you hear command exit open only",
  "You are seated next to the emergency exit would you be willing to open this in emergency pause":"You emergency exit next seated emergency pause open willing",
  "In that case may I please change your seat":"That case (situation) please I your seat change",
  "crew shall change the seat once the boarding is over":"Once boarding over crew seat change",
  "Point Towards the tray table and safety instruction card":"Safety instruction card and tray table point",
  "The instruction to open this exit window is printed here":"Window exit open instruction printed here",
  "A cabin crew member must check the language preference at the start of all briefings.":"All briefings start (first) cabin crew language preference check must",
  "Excuse me sir madam would you like me to brief you in English":"Excuse me sir madam you like (want) me English brief",
  "The following crew brief the over wing exit row passenger post completion of boarding once all passengers are seated":"Once all passengers seated passenger over wing exit row following crew brief completion post boarding",
  "She would take the consent from the passenger seated on the exit seats either through a node or a verbal confirmation":"She take (want) passenger seated exit seat consent Confirmation Node or verbal",
  "the occupied seat closer to the exit shall be deemed as the exit seat.":"Exit closer seat occupied exit seat deemed",
  "Crew shell remove the safety instruction card from the seat pocket and show it to the passenger and brief the passenger simultaneously.":"Crew Seat pocket safety instruction card remove and passenger show and simultaneously passenger brief",
  "Should a passenger refuse to assist (at the designated exit row seat) he she should immediately be reseated (seat changed) with minimum delay":"Passenger assist refuse (exit row seat designated) he she reseated immediately (seat change) delay minimum",
  "I shall come back to you after takeoff.":"Take off after I you come back",
  "The passenger may be allowed to sit on the original seat post takeoff but must be Reseated (on relocated seat) before landing.":"Takeoff post original seat passenger sit allow but reseated landing before must (on seat relocated)",
  "If any passenger is not able to understand the language":"If any passenger language understand not",
  "Should the passenger not pay attention":"Passenger attention (watch sign use towards signer) not",
  "either looking at their phones or listening to music":"Their Phones looking or music listening",
  "Ladies and gentlemen, the Captain has turned on the Fasten Seat Belt sign.":"Ladies and gentlemen, captain fasten seat belt sign turn on",
  "Please stow your carry-on luggage underneath the seat in front of you or in an overhead bin.":"please your luggage carry you front seat underneath stow or bin overhead",
  "Please take your seat and fasten your seat belt.":"Please your seat take and your seat belt fasten",
  "make sure your seat back and folding trays are in their full upright position.":"Your back seat make sure (remember) their trays folding position upright full",
  "If you are seated next to an emergency exit, please read carefully the special instructions card located by your seat.":"If you exit emergency next (near) seated, please special instruction card located your seat carefully read",
  "If you do not wish to perform the functions described in the event of an emergency, please ask a flight attendant to reseat you.":"If you emergency event described functions perform wish (want) not, please flight attendant ask (say) you reseat",
  "We remind you that this is a non-smoking flight.":"We you remind (inform) this flight non smoking",
  "Smoking is prohibited on the entire aircraft, including the lavatories.":"Aircraft entire smoking prohibited, lavatories including.",
  "Tampering with, disabling or destroying the lavatory smoke detectors is prohibited by law.":"Lavatory smoke detectors destroying, disabling or tampering with law by (inside) prohibited",
  "If you have any questions about our flight today, please do not hesitate to ask one of our flight attendants.":"If you any questions today our about flight, please our flight attendants ask hesitate not",
  "At this time, make sure your seat backs and tray tables are in their full upright position and that your seat belt is correctly fastened.":"Your back seat make sure (remember) their trays folding position upright full and your seat belt fastened correctly",
  "Also, your portable electronic devices must be set to ‘airplane’ mode until an announcement is made upon arrival. Thank you.":"Also, your portable electronic devices airplane mode must until (time +number +what) arrival announcement. thank you",
  "When the door is closed and the aircraft is about to pushback, the Captain or the Chief flight attendant will make an announcement intended to the flight attendants.":"When door closed and aircraft pushback, announcement captain or the flight chief attendant do flight attendants intended",
  "Flight attendants/Cabin Crew, please prepare for gate departure.":"Flight attendants/cabin crew, please gate departure prepare",
  "Flight attendants/Cabin Crew, doors on automatic, cross-check and report.":"Flight attendants / cabin crew, doors automatic, cross -check and report",
  "Flight attendants, prepare for take-off please.":"Please takeoff flight attendant prepare",
  "Cabin crew, please take your seats for take-off.":"Please take-off, cabin crew your seat take",
  "Ladies and gentlemen, the Captain has turned off the Fasten Seat Belt sign":"Ladies and gentlemen Captain seat belt fasten sign turn off (off)",
  "You may now move around the cabin.":"You cabin move now",
  "However, we always suggest to keep your seat belt fastened while you are seated.":"We suggest always if you seated your seat belt fastened",
  "In a few moments, the flight attendants will be passing around the cabin to offer you beverage, as well as breakfast/dinner/supper/a light meal/a snack.":"Flight attendants cabin passing (walking) few moment beverage +breakfast /dinner /supper /a light meal /a snack offer",
  "Alcoholic drinks are also available at a nominal charge/with our compliments.":"Alcoholic drinks nominal charge available our compliments",
  "On long flights with inflight entertainment: Also, we will be showing you our video presentation.":"flights long entertainment inflight : also we video presentation showing",
  "Flight attendants/Cabin crew, please be seated.":"Flight attendant / cabin crew please seated",
  "Ladies and gentlemen, captain has turned on the fasten seat belt sign.":"Ladies and gentlemen, captain seat belt fasten sign turn on.",
  "We are now crossing a zone of turbulence.":"we turbulence zone crossing now",
  "Please return your seats and keep your seat belts fastened. Thank you.":"Please your seat return and seat belt fastened thank you",
  "Ladies and gentlemen, as we start our descent, please make sure your seat backs and tray tables are in their full upright position.":"Ladies and gentlemen, we descent start, Your back seat make sure (remember) their trays folding position upright full",
  "Make sure your seat belt is securely fastened and all carry-on luggage is stowed underneath the seat in front of you or in the overhead bins.":"your seat belt fasten securely sure (remember) and all luggage carry you front seat underneath stow or bin overhead.",
  "Flight attendants, prepare for landing please.":"Please Flight attendants landing prepare",
  "Cabin crew, please take your seats for landing.":"Please cabin crew seats landing",
  "Please make sure one last time your seat belt is securely fastened.":"Please your seat belt fastened securely one last time sure (check)",
  "The flight attendants are currently passing around the cabin to make a final compliance check and pick up any remaining cups and glasses. Thank you.":"Flight attendants cabin currently passing (moving) check final compliance and remaining cups and glasses pick. thank you",
  "For your safety and comfort, please remain seated with your seat belt fastened until the Captain turns off the Fasten Seat Belt sign.":"Your safety and comfort, please you seated seatbelt fastened until captain seat belt fasten sign turn off",
  "This will indicate that we have parked at the gate and that it is safe for you to move about.":"This show we gate parked meaning you move safe",
  "Depending on the airline’s policy/local laws:":"Airlines policy /local laws depending",
  "At this time, you may use your cell phones if you wish.":"If you wish your cell phones use now possible",
  "Cellular phones may only be used once the Fasten Seat Belt sign has been turned off.":"Once seat belt fasten sign turned off (off) after cellular phone use only",
  "Please check around your seat for any personal belongings you may have brought on board with you and please use caution when opening the overhead bins, as heavy articles may have shifted around during the flight.":"Please any personal belonging you board time bought your seat around check and please overhead bins when opening caution use, flight during heavy articles shifted around",
  "If you require deplaning assistance, please remain in your seat until all other passenger’s ladies and gentlemen, have deplaned.":"If you deplaning assistance require, ladies and gentlemen please you seated until all other passenger deplaned",
  "One of our crew members will then be pleased to assist you.":"Our one crew members pleased you assist",
  "we are looking forward to seeing you on board again in the near future.":"We you future boarding again seeing looking forward (want)",
  "Have a nice day/evening/night/stay!":"Nice day /evening /night /stay",
  "Your items may be placed in an overhead compartment, or completely under the seat in front of you.":"Your items compartment overhead placed, or you front seat under completely",
  "Use caution when placing items in or removing them from the overhead compartment, and let us know if we may assist you.":"Caution use when items placing in and removing compartment overhead, and inform if we you assist",
  "In order to expedite the boarding process, please be seated as quickly as possible after stowing your carry-on items.":"Boarding process expedite, please seated quickly your items carry stowing after",
  "Take a moment to review the “Safety Instructions” card in your seat pocket.":"Review moment your seat pocket safety instruction card",
  "Passengers seated in row(s) (add specific exit row(s) for A/C type) are also asked to review the exit row seating requirements.":"Passenger seated row (A/C type specific exit row) review asked exit row seating requirements",
  "If you are seated in an exit row, you may be required to assist the crew in an evacuation.":"If you seated exit row, you required evacuation crew assist",
  "If you are unable or unwilling to perform the functions described on the card, just ask to be re-seated.":"If you unable or unwilling function perform card described, reseated ask.",
  "We are sorry for the delay in our departure.":"Our departure delay we sorry",
  "Please fasten your seat belt and refrain from smoking while the no smoking sign is on.":"Please your seatbelt fasten and smoking refrain while smoking no sign on.",
  "From captain and the crew, it is our pleasure to serve you today.":"captain and crew, today you serve our pleasure.",
  "If there is anything we can do to make your flight more enjoyable, please let us know.":"if anything we your flight enjoyable more, please inform.",
  "In a few moments we'll be screening a safety Video about this aircraft.":"Aircraft safety video we screening (show) few moments.",
  "you'll also find a safety briefing card in the seat pocket in front of you. We require that you give us your careful attention.":"you front seat pocket safety briefing card find. we require your careful attention",
  "The use of all radio transmitting devices is banned at all times as they can interfere with the aircraft instruments.":"All radio transmitting devices all times banned, they aircraft instrument with interfere",
  "All portable electronic devices like Walkman’s, computers, calculators, must be turned off during takeoff & landing and cell-phones must not be used at any time.":"All electronic portable devices, like (example) Walkman’s, computers, calculator turned off takeoff and landing and cell-phones any time use not",
  "For your safety, all passengers are kindly requested to refrain from using portable telephones, televisions, cd players, or FM radios in the cabin. Thank you.":"You safety, all passengers requested refrain cabin portable telephone television, CD player or FM radios using, thank you",
  "We are waiting for take-off (landing) clearance from the Air Traffic Control tower.":"We take off clearance waiting air traffic control tower",
  "We will be taking off shortly.":"We take off shortly",
  "Please make sure that your seat belt is securely fastened. Thank you.":"Please remember your seatbelt fastened securely. Thank you.",
  "May I have your attention, please?":"Your attention please?",
  "The fasten seat belt sign is now off.":"Seatbelt fasten sign now off",
  "However, we would suggest that you do keep your seat belt fastened during the entire flight.":"We flight entire (full time) suggest your seat belt fastened",
  "Your cooperation will be appreciated.":"Your cooperation appreciated",
  "For your enjoyment during our flight today, we have placed a complimentary copy of our in-flight magazine, Pacific Way, in the seat pocket in front of you.":"Today our flight during your enjoyment, we our inflight magazine complimentary copy placed, pacific way, you front seat pocket",
  "If you wish, please feel free to take this with you when you leave.":"If you wish please feel free when leave take with u",
  "Those interested in buying duty free goods will also find our sky-shop brochure in the seat pocket.":"Those duty free goods also our sky shop brochure find seat pocket buying interested",
  "If you are in the First or Business class sections, you will find controls for your reading flight, call button and the in-flight entertainment system on the inside of your seat armrest.":"If you first or business class section, you controls find reading flight, call button and inflight entertainment system your seat armrest inside",
  "In the economy cabin, these controls are located on top your seat armrest.":"cabin economy, these controls located your seat armrest top",
  "To adjust your seat, push the round bottom beside the panel.":"Your seat adjust, round bottom panel beside push",
  "Toilets for passengers seated in the economy cabins are located at the front, middle and rear of these cabins.":"Passengers seated cabins economy toilets located these cabins front, middle and rear",
  "Tea, coffee and a full bar service will be available throughout the flight.":"Flight throughout (full +time) service tea, coffee and bar available",
  "If you require any special assistance, please contact a flight attendant nearest you.":"If any special assistance (help) you require, flight attendant you nearest contact (say)",
  "We are here to ensure that you have a comfortable and enjoyable flight.":"We here ensure (check) flight you comfortable and enjoyable",
  "Later on we'll dim the cabin lights so you can get some rest.":"We cabin light dim later reason you rest",
  "We suggest that while asleep, you keep your seatbelt fastened over the top of your blanket.":"We suggest asleep while you seatbelt fasten blanket top",
  "This way it will not be necessary to wake you up should the seatbelt sign come on during the flight.":"Flight during seat belt sign show you wake up necessary (important) not",
  "If you don't want to be waken for breakfast, please advise a flight attendant. Thank you.":"Please flight attendant advise, if you breakfast waken want not. thank you",
  "We hope you have enjoyed the in-flight entertainment.":"You inflight entertainment enjoy we hope",
  "We are now preparing to land.":"We land preparing now",
  "The bar is closed and we will soon collect your headset.":"Your headset we collect bar soon (short + time) closed",
  "May I remind you to complete your arrival and immigration documentation by the time we arrive.":"I remind you your arrival complete and we arrive immigration documentation time",
  "Prepare for landing":"Landing prepare",
  "Personal television screens, footrests and seat tables must be stowed away and all hand luggage stored either in the overhead lockers or under the seat in front.":"Personal television screens, footrests and seat tables away stowed must and all luggage hand stored lockers overhead or front seat under",
  "Please ensure all electronic devices including laptop computers and computer games are turned off.":"Please ensure (remember) All electronic devices like (example) laptop, computer and computer games turned off",
  "This is your captain speaking.":"Your captain speaking",
  "If the weather cooperates we should get a great view of the city as we descend.":"If weather cooperate when we descend city view great.",
}

def airportStaticAnnouncements():
  return airport_static
